//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentForRoom.DBContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLNhaTroEntities : DbContext
    {
        public QLNhaTroEntities()
            : base("name=QLNhaTroEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbGioiThieu> tbGioiThieux { get; set; }
        public virtual DbSet<tbQuanHuyen> tbQuanHuyens { get; set; }
        public virtual DbSet<tbTinhThanhPho> tbTinhThanhPhoes { get; set; }
        public virtual DbSet<tbXaPhuong> tbXaPhuongs { get; set; }
        public virtual DbSet<tbQuyen> tbQuyens { get; set; }
        public virtual DbSet<tbUser> tbUsers { get; set; }
        public virtual DbSet<tbBanner> tbBanners { get; set; }
        public virtual DbSet<tbAlbum> tbAlbums { get; set; }
        public virtual DbSet<tbDatLich> tbDatLiches { get; set; }
        public virtual DbSet<tbChiTietPhong> tbChiTietPhongs { get; set; }
    }
}
