//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentForRoom.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbDatLich
    {
        public int IDDatLich { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<int> SoNguoiO { get; set; }
        public Nullable<int> SoLuongXe { get; set; }
        public Nullable<System.DateTime> NgayXemPhong { get; set; }
        public Nullable<System.DateTime> NgayChuyenVao { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> ThuCung { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
