//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentForRoom.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbGioiThieu
    {
        public int IDGioiThieu { get; set; }
        public string TieuDe { get; set; }
        public string NoiDung { get; set; }
        public string HinhAnh { get; set; }
        public string TieuDeDanhSach { get; set; }
        public string NoiDungDanhSach { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
