//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentForRoom.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbQuanHuyen
    {
        public Nullable<int> IDTP { get; set; }
        public string TenQuan { get; set; }
        public int IDQuan { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
