//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentForRoom.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUser
    {
        public int IDUser { get; set; }
        public Nullable<int> MaTaiKhoan { get; set; }
        public Nullable<int> Role { get; set; }
        public string SDT { get; set; }
        public string MatKhau { get; set; }
        public string HoTen { get; set; }
        public string Gmail { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<bool> Hide { get; set; }
    }
}
